export const examList1 = [
  {
    id: 1,
    type: '生存',
    time: '2025/1/1',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 2,
    type: '建筑',
    time: '2025/1/2',
    status: '请查收',
    showScore: 0,
    score: 40,
    state: 0,
    stateDisplay: false,
  },
  {
    id: 3,
    type: '红石',
    time: '2025/1/3',
    status: '批改中',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 4,
    type: 'PVP',
    time: '2025/1/4',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 5,
    type: '生存',
    time: '2025/1/5',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 1,
    type: '生存',
    time: '2025/1/6',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 2,
    type: '生存',
    time: '2025/1/7',
    status: '批改中',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 3,
    type: '生存',
    time: '2025/1/8',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 4,
    type: '生存',
    time: '2025/1/9',
    status: '请查收',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
  {
    id: 5,
    type: '生存',
    time: '2025/1/10',
    status: '批改中',
    showScore: 0,
    score: 80,
    state: 1,
    stateDisplay: false,
  },
];
